---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# CohortPlat

<!-- badges: start -->
<!-- badges: end -->

The goal of CohortPlat is to facilitate the simulation of cohort platform trials for combination treatments with binary endpoints.

## Installation

You can install the released version of CohortPlat from [CRAN](https://CRAN.R-project.org) with:

``` r
install.packages("CohortPlat")
```

And the development version from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("el-meyer/CohortPlat")
```

## Usage

Please see the [reference manual](https://el-meyer.github.io/CohortPlat/) for more information on the usage of this package, or jump directly to the [vignette](https://el-meyer.github.io/CohortPlat/articles/my-vignette.html).


## Disclaimer

EU-PEARL (EU Patient-cEntric clinicAl tRial pLatforms) project has received funding from the Innovative Medicines Initiative (IMI) 2 Joint Undertaking (JU) under grant agreement No 853966. This Joint Undertaking receives support from the European Union’s Horizon 2020 research and innovation program and EFPIA and Children’s Tumor Foundation, Global Alliance for TB Drug Development non-profit organization, Springworks Therapeutics Inc. This publication reflects the authors’ views. Neither IMI nor the European Union, EFPIA, or any Associated Partners are responsible for any use that may be made of the information contained herein. The research of Elias Laurin Meyer was funded until 11/2020 by Novartis through the University and not at an individual level.
